### ISSUE TITLE
 'npm install' error

### ISSUE THREAD

**Issue by YaraAmin** [vladmandic/nudenet#12]
Hi 
Thank you for sharing this repo! 
I cloned the repo but I'm getting the following error with 'npm install' 
<img width="1368" alt="Screenshot 2023-11-08 at 7 21 02 PM" src="https://github.com/vladmandic/nudenet/assets/39717801/3b40ae13-e177-471e-a2f5-d7792811fcff">
your help is appreciated! Thanks

**Comment by YaraAmin** [comment]
Also if there is a module/package for this repo as the original one in python it'd be amazing to use

**Comment by vladmandic** [comment]
this is a general issue with installation of `tfjs-node` on apple (not specific to this repo at all).
you may want to check `https://github.com/tensorflow/tfjs` for help.

regarding python, check out <https://github.com/vladmandic/sd-extension-nudenet/blob/main/nudenet.py>

**Comment by paramsinghvc** [comment]
Is there a nodejs version of this library? Would be great to use it on a node server to filter out nsfw images on the fly. @vladmandic
