### ISSUE TITLE
False positive matches in some shapes if input image resolution is high (1920x1080)

### ISSUE THREAD

**Issue by mpisat** [vladmandic/nudenet#5]
This is a bit weird, but considering the model size is smaller, I don't know if something happened during the conversion process. I don't know how NN works, I only use them for hobby purposes.

for testing, I used an image file with 1920x1080 screen capture from a browser with a female photo inside. It thinks some punch-hole sections of the headboard (bed) are exposed anus. 

if I resize image to 640x360 and test again, then it's fine. I don't know how much it will affect real nudity detection in that case though.

when I use python version of nudenet, the output is:
root@ubuntu22:~# python3 nn.py input_resized.jpg # this one is 640x360 resize
[{'box': [218, 96, 288, 158], 'score': 0.881401538848877, 'label': 'FACE_F'}]
root@ubuntu22:~# python3 nn.py 1920x1080.png
[{'box': [654, 289, 866, 479], 'score': 0.8705939650535583, 'label': 'FACE_F'}]

I used this command to resize: 
convert 1920x1080.png -resize 640x360\! input_resized.jpg

node.js version of the tests:
2023-03-25 12:50:00 STATE: loaded graph model: file:///root/src/nudenet/model/model.json
2023-03-25 12:50:01 INFO:  loaded image: 1920x1080.png width: 1920 height: 1080
2023-03-25 12:50:02 DATA:  result: {
  input: { file: '1920x1080.png', width: 1920, height: 1080 },
  person: true,
  sexy: false,
  nude: true,
  parts: [
    { score: 0.678825318813324, id: 6, class: 'female face', box: [ 657, 290, 173, 198 ] },
    { score: 0.445211261510849, id: 0, class: 'exposed anus', box: [ 1024, 98, 121, 137 ] },
    { score: 0.37644872069358826, id: 0, class: 'exposed anus', box: [ 1256, 127, 110, 137 ] },
    { score: 0.370495468378067, id: 0, class: 'exposed anus', box: [ 1233, 341, 83, 109 ] }
  ]
}

and if I use 640x360
2023-03-25 12:56:00 STATE: loaded graph model: file:///root/src/nudenet/model/model.json
2023-03-25 12:56:00 INFO:  loaded image: /root/input_resized.jpg width: 640 height: 360
2023-03-25 12:56:00 DATA:  result: {
  input: { file: '/root/input_resized.jpg', width: 640, height: 360 },
  person: true,
  sexy: false,
  nude: false,
  parts: [ { score: 0.6027270555496216, id: 6, class: 'female face', box: [ 218, 90, 59, 67 ] } ]
}

as you can see, score of is way lower than Python version.

**So my question is:**
1. How can we improve score compared to Python version? I don't mind using full 140Mb model file
2. What is the optimal image size for nudity detection? Should I resize every image to avoid those exposed anus false positives?

headboard -- false positive (crop of the full sized image output) is below:
https://murat.run/dl/headboard.png

**Comment by vladmandic** [comment]
thanks for the detailed report, this should be enough for me to analyze, i'll update when i have something.

**Comment by mpisat** [comment]
I can provide much more images in a zip or tar file if you should require them.

**Comment by vladmandic** [comment]
> I can provide much more images in a zip or tar file if you should require them.

if you can upload somewhere 2-3, it would be useful, no need for more.

**Comment by mpisat** [comment]
4 images -- puppeteer screen capture. You can test them with nudenet python to compare.

https://murat.run/dl/1.png
https://murat.run/dl/2.png
https://murat.run/dl/3.png
https://murat.run/dl/4.png

Images are not explicit except for 2.png where the female is topless (but not fully naked)

**Comment by mpisat** [comment]
**default-f16 model performs better than before, and I really appreciate your time on this.**
however, side by side comparisons:

frhb64652ds ~ # FILE_PATH='/home/admin/murat.run/dl/1.png' ENDPOINT="http://localhost:8040/sync" ./nn
{
 "prediction": {
  "file_name": [
   {
    "box": [
     710,
     337,
     841,
     430
    ],
    "score": 0.8690894246101379,
    "label": "EXPOSED_BUTTOCKS"
   },
   {
    "box": [
     550,
     335,
     671,
     420
    ],
    "score": 0.866243302822113,
    "label": "EXPOSED_BELLY"
   },
   {
    "box": [
     483,
     94,
     549,
     161
    ],
    "score": 0.7957088947296143,
    "label": "FACE_F"
   },
   {
    "box": [
     507,
     231,
     630,
     331
    ],
    "score": 0.706888735294342,
    "label": "COVERED_BREAST_F"
   },
   {
    "box": [
     588,
     423,
     639,
     465
    ],
    "score": 0.6685518026351929,
    "label": "COVERED_GENITALIA_F"
   }
  ]
 },
 "success": true
}

vs

2023-03-28 05:16:25 INFO:  undefined version undefined
2023-03-28 05:16:25 INFO:  User: root Platform: linux Arch: x64 Node: v18.15.0
2023-03-28 05:16:25 INFO:  tfjs version: 4.3.0 backend: tensorflow
2023-03-28 05:16:25 INFO:  options: {
  debug: true,
  modelPath: 'file:///root/nudenet/models/default-f16/model.json',
  minScore: 0.38,
  maxResults: 50,
  iouThreshold: 0.5,
  outputNodes: [ 'output1', 'output2', 'output3' ],
  blurNude: false,
  blurRadius: 25
}
2023-03-28 05:16:26 STATE: loaded graph model: file:///root/nudenet/models/default-f16/model.json
2023-03-28 05:16:26 INFO:  loaded image: 1.png width: 1280 height: 720
2023-03-28 05:16:27 DATA:  result: {
  input: { file: '1.png', width: 1280, height: 720 },
  person: true,
  sexy: true,
  nude: true,
  parts: [
    { score: 0.6367054581642151, id: 5, class: 'exposed buttocks', box: [ 710, 332, 98, 129 ] },
    { score: 0.6157164573669434, id: 4, class: 'buttocks', box: [ 710, 333, 97, 128 ] },
    { score: 0.5851989984512329, id: 10, class: 'breast', box: [ 497, 223, 107, 127 ] },
    { score: 0.5644777417182922, id: 6, class: 'female face', box: [ 487, 88, 67, 55 ] }
  ]
}

Second file:

FILE_PATH='/home/admin/murat.run/dl/2.png' ENDPOINT="http://localhost:8040/sync" ./nn
{
 "prediction": {
  "file_name": [
   {
    "box": [
     393,
     279,
     519,
     394
    ],
    "score": 0.9579517841339111,
    "label": "EXPOSED_BELLY"
   },
   {
    "box": [
     371,
     183,
     457,
     257
    ],
    "score": 0.9398015737533569,
    "label": "EXPOSED_BREAST_F"
   },
   {
    "box": [
     477,
     188,
     563,
     270
    ],
    "score": 0.9302072525024414,
    "label": "EXPOSED_BREAST_F"
   },
   {
    "box": [
     435,
     403,
     491,
     447
    ],
    "score": 0.8589361310005188,
    "label": "COVERED_GENITALIA_F"
   },
   {
    "box": [
     359,
     154,
     393,
     202
    ],
    "score": 0.828746497631073,
    "label": "EXPOSED_ARMPITS"
   },
   {
    "box": [
     432,
     62,
     520,
     123
    ],
    "score": 0.7842403650283813,
    "label": "FACE_F"
   }
  ]
 },
 "success": true
}

vs

2023-03-28 05:16:27 STATE: loaded graph model: file:///root/nudenet/models/default-f16/model.json
2023-03-28 05:16:27 INFO:  loaded image: 2.png width: 1280 height: 720
2023-03-28 05:16:28 DATA:  result: {
  input: { file: '2.png', width: 1280, height: 720 },
  person: true,
  sexy: true,
  nude: true,
  parts: [
    { score: 0.9074488282203674, id: 3, class: 'exposed belly', box: [ 392, 271, 117, 125 ] },
    { score: 0.8766870498657227, id: 11, class: 'exposed breast', box: [ 366, 176, 82, 91 ] },
    { score: 0.7965465784072876, id: 11, class: 'exposed breast', box: [ 471, 184, 80, 88 ] },
    { score: 0.7253260016441345, id: 12, class: 'vagina', box: [ 432, 398, 42, 57 ] },
    { score: 0.7064149975776672, id: 6, class: 'female face', box: [ 432, 64, 62, 86 ] },
    { score: 0.5549026131629944, id: 1, class: 'exposed armpits', box: [ 357, 155, 47, 34 ] }
  ]
}

I don't think quantization is affecting these scores. ****

**Comment by mpisat** [comment]
Also, may I know what tensorflowjs_converter command you used to get this default-f16 output? I thought you used [detector_v2_default_checkpoint_tf.tar](https://github.com/notAI-tech/NudeNet/releases/download/v0/detector_v2_default_checkpoint_tf.tar) in the original model.

**Comment by vladmandic** [comment]
yes, that's the correct url to model.  
command used for conversion is;  

```shell
tensorflowjs_convetensorflowjs_converter \
--input_format tf_saved_model \
--output_format tfjs_graph_model \
--strip_debug_ops=* \
--signature_name=predict \
--saved_model_tags=serve \
--weight_shard_size_bytes=16777216 \
--quantize_float16=* \
detector_v2_base_checkpoint_tf base-int16
```
